package Procesamientos;

import asint.SintaxisAbstractaTiny.Acc_reg;
import asint.SintaxisAbstractaTiny.And;
import asint.SintaxisAbstractaTiny.Asignacion;
import asint.SintaxisAbstractaTiny.Bloque;
import asint.SintaxisAbstractaTiny.Bool_t;
import asint.SintaxisAbstractaTiny.Cadena;
import asint.SintaxisAbstractaTiny.Comparacion;
import asint.SintaxisAbstractaTiny.Dec_proc;
import asint.SintaxisAbstractaTiny.Dec_tipo;
import asint.SintaxisAbstractaTiny.Dec_var;
import asint.SintaxisAbstractaTiny.Distinto;
import asint.SintaxisAbstractaTiny.Div;
import asint.SintaxisAbstractaTiny.Exp;
import asint.SintaxisAbstractaTiny.False_e;
import asint.SintaxisAbstractaTiny.Iden;
import asint.SintaxisAbstractaTiny.Indexacion;
import asint.SintaxisAbstractaTiny.Indireccion;
import asint.SintaxisAbstractaTiny.Inst_call;
import asint.SintaxisAbstractaTiny.Inst_comp;
import asint.SintaxisAbstractaTiny.Inst_delete;
import asint.SintaxisAbstractaTiny.Inst_eval;
import asint.SintaxisAbstractaTiny.Inst_if_else;
import asint.SintaxisAbstractaTiny.Inst_new;
import asint.SintaxisAbstractaTiny.Inst_nl;
import asint.SintaxisAbstractaTiny.Inst_read;
import asint.SintaxisAbstractaTiny.Inst_while;
import asint.SintaxisAbstractaTiny.Inst_write;
import asint.SintaxisAbstractaTiny.Int_t;
import asint.SintaxisAbstractaTiny.LParam;
import asint.SintaxisAbstractaTiny.LParamForm;
import asint.SintaxisAbstractaTiny.LParamReg;
import asint.SintaxisAbstractaTiny.Lit_ent;
import asint.SintaxisAbstractaTiny.Lit_real;
import asint.SintaxisAbstractaTiny.Mayor;
import asint.SintaxisAbstractaTiny.Mayor_igual;
import asint.SintaxisAbstractaTiny.Menor;
import asint.SintaxisAbstractaTiny.Menor_igual;
import asint.SintaxisAbstractaTiny.Mod;
import asint.SintaxisAbstractaTiny.Muchas_lista_decs;
import asint.SintaxisAbstractaTiny.Muchas_lista_inst;
import asint.SintaxisAbstractaTiny.Muchas_lista_param;
import asint.SintaxisAbstractaTiny.Muchas_lista_param_form;
import asint.SintaxisAbstractaTiny.Muchas_lista_param_reg;
import asint.SintaxisAbstractaTiny.Mult;
import asint.SintaxisAbstractaTiny.No_else;
import asint.SintaxisAbstractaTiny.No_lista_opt_decs;
import asint.SintaxisAbstractaTiny.No_lista_opt_inst;
import asint.SintaxisAbstractaTiny.No_lista_opt_param;
import asint.SintaxisAbstractaTiny.No_lista_opt_param_form;
import asint.SintaxisAbstractaTiny.Not_unario;
import asint.SintaxisAbstractaTiny.Null_e;
import asint.SintaxisAbstractaTiny.Or;
import asint.SintaxisAbstractaTiny.Param_form;
import asint.SintaxisAbstractaTiny.Param_form_ref;
import asint.SintaxisAbstractaTiny.Param_reg;
import asint.SintaxisAbstractaTiny.Prog_tiny;
import asint.SintaxisAbstractaTiny.Real_t;
import asint.SintaxisAbstractaTiny.Resta;
import asint.SintaxisAbstractaTiny.Resta_unario;
import asint.SintaxisAbstractaTiny.Si_else;
import asint.SintaxisAbstractaTiny.Si_lista_opt_decs;
import asint.SintaxisAbstractaTiny.Si_lista_opt_inst;
import asint.SintaxisAbstractaTiny.Si_lista_opt_param;
import asint.SintaxisAbstractaTiny.Si_lista_opt_param_form;
import asint.SintaxisAbstractaTiny.String_t;
import asint.SintaxisAbstractaTiny.Suma;
import asint.SintaxisAbstractaTiny.Tipo;
import asint.SintaxisAbstractaTiny.Tipo_array;
import asint.SintaxisAbstractaTiny.Tipo_definido;
import asint.SintaxisAbstractaTiny.Tipo_puntero;
import asint.SintaxisAbstractaTiny.Tipo_registro;
import asint.SintaxisAbstractaTiny.True_e;
import asint.SintaxisAbstractaTiny.Una_lista_dec;
import asint.SintaxisAbstractaTiny.Una_lista_inst;
import asint.SintaxisAbstractaTiny.Una_lista_param;
import asint.SintaxisAbstractaTiny.Una_lista_param_form;
import asint.SintaxisAbstractaTiny.Una_lista_param_reg;

public interface IProcesamientoT{
	void tipado(Prog_tiny p);
	void tipado(Bloque p);
	void tipado(Si_lista_opt_decs p);
	void tipado(No_lista_opt_decs p);
	void tipado(Muchas_lista_decs p);
	void tipado(Una_lista_dec p);
	void tipado(Dec_var p);
	void tipado(Dec_tipo p);
	void tipado(Dec_proc p);
	//void tipado(Si_lista_opt_param_form p);
	//void tipado(No_lista_opt_param_form p);
	//void tipado(Muchas_lista_param_form p);
	// tipado(Una_lista_param_form p);
	//void tipado(Param_form_ref p);
	//void tipado(Param_form p);
	void tipado(Tipo_array p);
	void tipado(Tipo_puntero p);
	void tipado(Int_t p);
	void tipado(Real_t p);
	void tipado(Bool_t p);
	void tipado(String_t p);
	void tipado(Tipo_registro p);
	void tipado(Tipo_definido p);
	void tipado(Muchas_lista_param_reg p);
	void tipado(Una_lista_param_reg p);
	void tipado(Param_reg p);
	void tipado(Si_lista_opt_inst p);
	void tipado(No_lista_opt_inst p);
	void tipado(Muchas_lista_inst p);
	void tipado(Una_lista_inst p);
	void tipado(Inst_eval p);
	void tipado(Inst_if_else p);
	void tipado(Si_else p);
	void tipado(No_else p);
	void tipado(Inst_while p);
	void tipado(Inst_read p);
	void tipado(Inst_write p);
	void tipado(Inst_nl p);
	void tipado(Inst_new p);
	void tipado(Inst_delete p);
	void tipado(Inst_call p);
	void tipado(Inst_comp p);
	void tipado(Si_lista_opt_param p);
	void tipado(No_lista_opt_param p);
	void tipado(Muchas_lista_param p);
	void tipado(Una_lista_param p);
	void tipado(Asignacion p);
	void tipado(Mayor p);
	void tipado(Mayor_igual p);
	void tipado(Menor p);
	void tipado(Menor_igual p);
	void tipado(Comparacion p);
	void tipado(Distinto p);
	void tipado(Suma p);
	void tipado(Resta p);
	void tipado(And p);
	void tipado(Or p);
	void tipado(Mult p);
	void tipado(Div p);
	void tipado(Mod p);
	void tipado(Not_unario p);
	void tipado(Resta_unario p);
	void tipado(Indexacion p);
	void tipado(Acc_reg p);
	void tipado(Indireccion p);
	void tipado(Lit_ent p);
	void tipado(Lit_real p);
	void tipado(True_e p);
	void tipado(False_e p);
	void tipado(Null_e p);
	void tipado(Cadena p);
	void tipado(Iden p);
	boolean compatibles(Tipo t1,Tipo T2);
	boolean compatibles_registro(LParamReg l1, LParamReg l2);
	boolean compatibles_proc(LParam lp, LParamForm lpf);
	boolean es_designador(Exp e);
	boolean ambos_ok(Tipo T0,Tipo T1);
	
	
}
