package alex;

public enum ClaseLexica {
	MENOSUNARIO, NOT, POR, ENTRE, AND, OR, 
	MAS, MENOS, MENOR, 
	Entero, Real, Booleano, Identificador,
	MAYOR, MENORIGUAL, MAYORIGUAL, 
	COMPARACION, DISTINTO, ASIGNACION, 
	INIPAR, FINPAR, 
	INIBLOQUE, FINBLOQUE, 
	ARROBA, FINDECLARACIONES, PUNTOYCOMA, EOF,
	
	INT, REAL, BOOL, STRING,
	NULL, TRUE, FALSE, PROC, IF, ELSE, WHILE, STRUCT, NEW, DELETE, READ, WRITE, NL, TYPE, CALL, 
}
