package alex;

public enum ClaseLexica {
	MENOSUNARIO, NOT, POR, ENTRE, AND, OR, 
	MAS, MENOS, MENOR, 
	Entero, Real, Booleano, 
	MAYOR, MENORIGUAL, MAYORIGUAL, 
	COMPARACION, DISTINTO, ASIGNACION, 
	INIPAR, FINPAR, 
	INIBLOQUE, FINBLOQUE, 
	ARROBA, FINDECLARACIONES, PUNTOYCOMA, EOF
}
