/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package javaccDesc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int parteExponencial = 6;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int REAL = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int NULL = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int PROC = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int STRUCT = 23;
  /** RegularExpression Id. */
  int NEW = 24;
  /** RegularExpression Id. */
  int DELETE = 25;
  /** RegularExpression Id. */
  int READ = 26;
  /** RegularExpression Id. */
  int WRITE = 27;
  /** RegularExpression Id. */
  int NL = 28;
  /** RegularExpression Id. */
  int TYPE = 29;
  /** RegularExpression Id. */
  int CALL = 30;
  /** RegularExpression Id. */
  int POR = 31;
  /** RegularExpression Id. */
  int ENTRE = 32;
  /** RegularExpression Id. */
  int MAS = 33;
  /** RegularExpression Id. */
  int MENOS = 34;
  /** RegularExpression Id. */
  int MENOR = 35;
  /** RegularExpression Id. */
  int MENORIGUAL = 36;
  /** RegularExpression Id. */
  int MAYOR = 37;
  /** RegularExpression Id. */
  int MAYORIGUAL = 38;
  /** RegularExpression Id. */
  int COMPARACION = 39;
  /** RegularExpression Id. */
  int DISTINTO = 40;
  /** RegularExpression Id. */
  int ASIGNACION = 41;
  /** RegularExpression Id. */
  int INIPAR = 42;
  /** RegularExpression Id. */
  int FINPAR = 43;
  /** RegularExpression Id. */
  int INIBLOQUE = 44;
  /** RegularExpression Id. */
  int FINBLOQUE = 45;
  /** RegularExpression Id. */
  int ARROBA = 46;
  /** RegularExpression Id. */
  int FINDECLARACIONES = 47;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 48;
  /** RegularExpression Id. */
  int INIARRAY = 49;
  /** RegularExpression Id. */
  int FINARRAY = 50;
  /** RegularExpression Id. */
  int PUNTERO = 51;
  /** RegularExpression Id. */
  int MODULO = 52;
  /** RegularExpression Id. */
  int COMA = 53;
  /** RegularExpression Id. */
  int REFERENCIA = 54;
  /** RegularExpression Id. */
  int PUNTO = 55;
  /** RegularExpression Id. */
  int Identificador = 56;
  /** RegularExpression Id. */
  int Entero = 57;
  /** RegularExpression Id. */
  int Real = 58;
  /** RegularExpression Id. */
  int Cadena = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<INT>",
    "<REAL>",
    "<BOOL>",
    "<STRING>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<NULL>",
    "<TRUE>",
    "<FALSE>",
    "<PROC>",
    "<IF>",
    "<ELSE>",
    "<WHILE>",
    "<STRUCT>",
    "<NEW>",
    "<DELETE>",
    "<READ>",
    "<WRITE>",
    "<NL>",
    "<TYPE>",
    "<CALL>",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"&&\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"^\"",
    "\"%\"",
    "\",\"",
    "\"&\"",
    "\".\"",
    "<Identificador>",
    "<Entero>",
    "<Real>",
    "<Cadena>",
  };

}
