
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Apr 03 20:12:58 CEST 2024
//----------------------------------------------------

package c_ast_ascendente.asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int Entero = 50;
  public static final int DISTINTO = 20;
  public static final int POR = 22;
  public static final int PUNTOYCOMA = 5;
  public static final int FINARRAY = 10;
  public static final int Real = 51;
  public static final int INT = 39;
  public static final int INIBLOQUE = 2;
  public static final int REFERENCIA = 12;
  public static final int DELETE = 37;
  public static final int WRITE = 34;
  public static final int NOT = 27;
  public static final int MENORIGUAL = 18;
  public static final int AND = 24;
  public static final int TYPE = 44;
  public static final int OR = 25;
  public static final int BOOL = 41;
  public static final int CALL = 38;
  public static final int ARROBA = 14;
  public static final int IF = 30;
  public static final int Cadena = 52;
  public static final int MAYORIGUAL = 16;
  public static final int EOF = 0;
  public static final int TRUE = 46;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int FINDECLARACIONES = 4;
  public static final int MODULO = 26;
  public static final int MENOS = 29;
  public static final int NULL = 48;
  public static final int FINBLOQUE = 3;
  public static final int MENOR = 17;
  public static final int PUNTERO = 11;
  public static final int ASIGNACION = 21;
  public static final int REAL = 40;
  public static final int MAYOR = 15;
  public static final int ELSE = 31;
  public static final int PUNTO = 6;
  public static final int NL = 35;
  public static final int READ = 33;
  public static final int WHILE = 32;
  public static final int Identificador = 49;
  public static final int FINPAR = 8;
  public static final int INIARRAY = 9;
  public static final int PROC = 45;
  public static final int STRING = 42;
  public static final int COMPARACION = 19;
  public static final int FALSE = 47;
  public static final int STRUCT = 43;
  public static final int ENTRE = 23;
  public static final int INIPAR = 7;
  public static final int MAS = 28;
}

