package alex;

public enum ClaseLexica {
	
	PUNTO, NOT, POR, ENTRE, AND, OR, 
	MAS, MENOS, MENOR, 
	Entero, Real,
	MAYOR, MENORIGUAL, MAYORIGUAL, 
	COMPARACION, DISTINTO, ASIGNACION, 
	INIPAR, FINPAR,
	INIBLOQUE, FINBLOQUE, 
	ARROBA, FINDECLARACIONES, PUNTOYCOMA, EOF, Identificador,
	Cadena, INT, REAL, BOOL, STRING, NULL, TRUE, FALSE,
	PROC, IF, ELSE, WHILE, STRUCT, NEW, DELETE, READ, WRITE,
	NL, TYPE, CALL, INIARRAY, FINARRAY, PUNTERO, MODULO, COMA, REFERENCIA;
}	
